PIN_ROOT := ../Abacus/Intel-Pin-Archive/
CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
TARGET := ia32

include $(CONFIG_ROOT)/makefile.config
include makefile.rules
include $(TOOLS_ROOT)/Config/makefile.default.rules
